name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  my_build_job
  runs-on: ubuntu-latest
  steps:
    - user: actions/checkoout@v3
    - name: npm install, test and build
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run JS file for test
      run: node script.js
